version: 2

flow:
  - name: kaniko-app-image
    type: eureka/kaniko:v2
    env:
      DOCKERFILE: .ci/app/Dockerfile
      CONTEXT: ./
      IMAGE_NAME: kraken-scheduler
      HELM_VALUES_FILE: .ci/charts/values.yaml
