/*
Copyright 2020 The Knative Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
	v1alpha1 "kraken.dev/kraken-scheduler/pkg/apis/scheduler/v1alpha1"
	scheme "kraken.dev/kraken-scheduler/pkg/client/clientset/versioned/scheme"
)

// IntegrationScenariosGetter has a method to return a IntegrationScenarioInterface.
// A group's client should implement this interface.
type IntegrationScenariosGetter interface {
	IntegrationScenarios(namespace string) IntegrationScenarioInterface
}

// IntegrationScenarioInterface has methods to work with IntegrationScenario resources.
type IntegrationScenarioInterface interface {
	Create(*v1alpha1.IntegrationScenario) (*v1alpha1.IntegrationScenario, error)
	Update(*v1alpha1.IntegrationScenario) (*v1alpha1.IntegrationScenario, error)
	UpdateStatus(*v1alpha1.IntegrationScenario) (*v1alpha1.IntegrationScenario, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.IntegrationScenario, error)
	List(opts v1.ListOptions) (*v1alpha1.IntegrationScenarioList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.IntegrationScenario, err error)
	IntegrationScenarioExpansion
}

// integrationScenarios implements IntegrationScenarioInterface
type integrationScenarios struct {
	client rest.Interface
	ns     string
}

// newIntegrationScenarios returns a IntegrationScenarios
func newIntegrationScenarios(c *SchedulerV1alpha1Client, namespace string) *integrationScenarios {
	return &integrationScenarios{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the integrationScenario, and returns the corresponding integrationScenario object, and an error if there is any.
func (c *integrationScenarios) Get(name string, options v1.GetOptions) (result *v1alpha1.IntegrationScenario, err error) {
	result = &v1alpha1.IntegrationScenario{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("integrationscenarios").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of IntegrationScenarios that match those selectors.
func (c *integrationScenarios) List(opts v1.ListOptions) (result *v1alpha1.IntegrationScenarioList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.IntegrationScenarioList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("integrationscenarios").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested integrationScenarios.
func (c *integrationScenarios) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("integrationscenarios").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a integrationScenario and creates it.  Returns the server's representation of the integrationScenario, and an error, if there is any.
func (c *integrationScenarios) Create(integrationScenario *v1alpha1.IntegrationScenario) (result *v1alpha1.IntegrationScenario, err error) {
	result = &v1alpha1.IntegrationScenario{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("integrationscenarios").
		Body(integrationScenario).
		Do().
		Into(result)
	return
}

// Update takes the representation of a integrationScenario and updates it. Returns the server's representation of the integrationScenario, and an error, if there is any.
func (c *integrationScenarios) Update(integrationScenario *v1alpha1.IntegrationScenario) (result *v1alpha1.IntegrationScenario, err error) {
	result = &v1alpha1.IntegrationScenario{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("integrationscenarios").
		Name(integrationScenario.Name).
		Body(integrationScenario).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *integrationScenarios) UpdateStatus(integrationScenario *v1alpha1.IntegrationScenario) (result *v1alpha1.IntegrationScenario, err error) {
	result = &v1alpha1.IntegrationScenario{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("integrationscenarios").
		Name(integrationScenario.Name).
		SubResource("status").
		Body(integrationScenario).
		Do().
		Into(result)
	return
}

// Delete takes name of the integrationScenario and deletes it. Returns an error if one occurs.
func (c *integrationScenarios) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("integrationscenarios").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *integrationScenarios) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("integrationscenarios").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched integrationScenario.
func (c *integrationScenarios) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.IntegrationScenario, err error) {
	result = &v1alpha1.IntegrationScenario{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("integrationscenarios").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
