/*
Copyright 2020 The Knative Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	time "time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
	schedulerv1alpha1 "kraken.dev/kraken-scheduler/pkg/apis/scheduler/v1alpha1"
	versioned "kraken.dev/kraken-scheduler/pkg/client/clientset/versioned"
	internalinterfaces "kraken.dev/kraken-scheduler/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "kraken.dev/kraken-scheduler/pkg/client/listers/scheduler/v1alpha1"
)

// IntegrationScenarioInformer provides access to a shared informer and lister for
// IntegrationScenarios.
type IntegrationScenarioInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.IntegrationScenarioLister
}

type integrationScenarioInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewIntegrationScenarioInformer constructs a new informer for IntegrationScenario type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewIntegrationScenarioInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredIntegrationScenarioInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredIntegrationScenarioInformer constructs a new informer for IntegrationScenario type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredIntegrationScenarioInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.SchedulerV1alpha1().IntegrationScenarios(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.SchedulerV1alpha1().IntegrationScenarios(namespace).Watch(options)
			},
		},
		&schedulerv1alpha1.IntegrationScenario{},
		resyncPeriod,
		indexers,
	)
}

func (f *integrationScenarioInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredIntegrationScenarioInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *integrationScenarioInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&schedulerv1alpha1.IntegrationScenario{}, f.defaultInformer)
}

func (f *integrationScenarioInformer) Lister() v1alpha1.IntegrationScenarioLister {
	return v1alpha1.NewIntegrationScenarioLister(f.Informer().GetIndexer())
}
