apiVersion: v1
kind: Service
metadata:
  name: integration-scheduler-controller
  namespace: integration-framework
  labels:
    scheduler.kraken.dev/release: "v0.13.0"
    control-plane: integration-scheduler-manager
spec:
  selector:
    control-plane: integration-scheduler-manager
  ports:
    - name: https-integration-scheduler
      port: 443