apiVersion: apps/v1
kind: Deployment
metadata:
  name: integration-scenario-scheduler
  namespace: integration-framework
  labels:
    scheduler.kraken.dev/release: "v0.13.0"
    control-plane: integration-scheduler-manager
spec:
  replicas: 1
  selector:
    matchLabels: &labels
      control-plane: integration-scheduler-manager
  template:
    metadata:
      labels: *labels
    spec:
      serviceAccountName: integration-scheduler-manager
      containers:
        - name: manager
          image: docker.io/sbcd90/controller-6c8bfaf77bd7905213fa6baffb1d2951:latest
          env:
            - name: SYSTEM_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: METRICS_DOMAIN
              value: knative.dev/sources
            - name: CONFIG_OBSERVABILITY_NAME
              value: config-observability
            - name: CONFIG_LEADERELECTION_NAME
              value: config-leader-election-integration-scheduler
            - name: WAITQUEUE_PRODUCER_IMAGE
              value: docker.io/sbcd90/test1:latest
            - name: WAITQUEUE_PROCESSOR_IMAGE
              value: docker.io/sbcd90/test2:latest
          volumeMounts:
          resources:
            requests:
              cpu: 20m
              memory: 20Mi
      serviceAccount: integration-scheduler-manager
      terminationGracePeriodSeconds: 10
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: integration-scenario-scheduler
  namespace: integration-framework
  labels:
    scheduler.kraken.dev/release: "v0.13.0"
    control-plane: integration-scheduler-manager
spec:
  replicas: 0
  selector:
    matchLabels: &labels
      control-plane: integration-scheduler-manager
  serviceName: integration-scheduler-manager
  template:
    metadata:
      labels: *labels
    spec:
      serviceAccountName: integration-scheduler-manager
      containers:
        - name: manager
          image: docker.io/sbcd90/controller-6c8bfaf77bd7905213fa6baffb1d2951:latest
          env:
            - name: SYSTEM_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: METRICS_DOMAIN
              value: knative.dev/sources
            - name: CONFIG_OBSERVABILITY_NAME
              value: config-observability
            - name: WAITQUEUE_PRODUCER_IMAGE
              value: docker.io/sbcd90/test1:latest
            - name: WAITQUEUE_PROCESSOR_IMAGE
              value: docker.io/sbcd90/test2:latest
          volumeMounts:
          resources:
            requests:
              cpu: 20m
              memory: 20Mi
      serviceAccount: integration-scheduler-manager
      terminationGracePeriodSeconds: 10