apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJoYXJib3IuZXVyZWthY2xvdWQuaW8iOnsidXNlcm5hbWUiOiJzdWJob2JyYXRhLmRleUBzYXAuY29tIiwicGFzc3dvcmQiOiJidDc0cU1ndTNlR0NqSkhRIiwiZW1haWwiOiJzdWJob2JyYXRhLmRleUBzYXAuY29tIiwiYXV0aCI6ImMzVmlhRzlpY21GMFlTNWtaWGxBYzJGd0xtTnZiVHBpZERjMGNVMW5kVE5sUjBOcVNraFIifX19
kind: Secret
metadata:
  name: docker-registry-secret
  namespace: integration-framework
type: kubernetes.io/dockerconfigjson
---
apiVersion: v1
kind: Secret
metadata:
  name: schema-registry-secret
  namespace: integration-framework
type: Opaque
data:
  storeCreds: N2VlMTllZjE1MzMyYWFjZWE1MDY3OTA4ZTgzN2JlYTE1ZGIwMDRkMQ==
---
apiVersion: v1
kind: Secret
metadata:
  name: tenant-onboarding-secret
  namespace: integration-framework
type: Opaque
data:
  tenantOnboardingTopic: S3Jha2VuVGVuYW50T25ib2FyZGluZw==
  intScnOnboardingTopic: S3Jha2VuSW50U2NlbmFyaW9PbmJvYXJkaW5n
  kafkaBrokerSASLPassword: UnFHTkhCaFN1S2hGUFU5VkFCcTIyVHVuR2FuMHhFaTBJOUUzdkpBUGFUU2xJbTFueGc3R2hjMzZvcDdkNGQxYg==
  kafkaBrokerSASLUser: WEJQWkFCRjNKRlpNT01IWQ==
  kafkaBroker: cGtjLTQzbjEwLnVzLWNlbnRyYWwxLmdjcC5jb25mbHVlbnQuY2xvdWQ6OTA5Mg==
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  namespace: integration-framework
type: Opaque
data:
  redisUrl: MTAuMjI0LjE3OS4yNDM6NjM3OQ==