apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJoYXJib3IuZXVyZWthY2xvdWQuaW8iOnsidXNlcm5hbWUiOiJzdWJob2JyYXRhLmRleUBzYXAuY29tIiwicGFzc3dvcmQiOiJidDc0cU1ndTNlR0NqSkhRIiwiZW1haWwiOiJzdWJob2JyYXRhLmRleUBzYXAuY29tIiwiYXV0aCI6ImMzVmlhRzlpY21GMFlTNWtaWGxBYzJGd0xtTnZiVHBpZERjMGNVMW5kVE5sUjBOcVNraFIifX19
kind: Secret
metadata:
  name: docker-registry-secret
  namespace: integration-framework
type: kubernetes.io/dockerconfigjson
---
apiVersion: v1
kind: Secret
metadata:
  name: schema-registry-secret
  namespace: integration-framework
type: Opaque
data:
  storeCreds: 