apiVersion: apps/v1
kind: Deployment
metadata:
  name: integration-scenario-scheduler
  namespace: integration-framework
  labels:
    scheduler.kraken.dev/release: "v0.13.0"
    control-plane: integration-scheduler-manager
spec:
  replicas: 1
  selector:
    matchLabels: &labels
      control-plane: integration-scheduler-manager
  template:
    metadata:
      labels: *labels
    spec:
      serviceAccountName: integration-scheduler-manager
      containers:
      - name: manager
        image: docker.io/sbcd90/kraken-scheduler-controller-cb08c04a0b73c7b0de5fe0905510ed76:latest
        env:
        - name: SYSTEM_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: METRICS_DOMAIN
          value: knative.dev/sources
        - name: CONFIG_OBSERVABILITY_NAME
          value: config-observability
        - name: CONFIG_LEADERELECTION_NAME
          value: config-leader-election-integration-scheduler
        - name: WAITQUEUE_PRODUCER_IMAGE
          value: harbor.eurekacloud.io/eureka/kraken-waitqueue-producer:31426118153dfe1c04e8d1c8232bb7d95ede5ebe
        - name: WAITQUEUE_PROCESSOR_IMAGE
          value: harbor.eurekacloud.io/eureka/kraken-waitqueue-processor:31426118153dfe1c04e8d1c8232bb7d95ede5ebe
        - name: SCHEMA_REGISTRY_STORE_CREDS
          valueFrom:
            secretKeyRef:
              name: schema-registry-secret
              key: storeCreds  
        volumeMounts:
        resources:
          requests:
            cpu: 20m
            memory: 20Mi
      serviceAccount: integration-scheduler-manager
      terminationGracePeriodSeconds: 10