apiVersion: apps/v1
kind: Deployment
metadata:
  name: integration-scenario-scheduler
  namespace: integration-framework
  labels:
    scheduler.kraken.dev/release: "v0.13.0"
    control-plane: integration-scheduler-manager
spec:
  replicas: 1
  selector:
    matchLabels: &labels
      control-plane: integration-scheduler-manager
  template:
    metadata:
      labels: *labels
    spec:
      serviceAccountName: integration-scheduler-manager
      containers:
      - name: manager
        image: harbor.eurekacloud.io/eureka/kraken-scheduler-controller-bc8b21eb9284f18ede3d1b99597b72f1:latest
        env:
        - name: SYSTEM_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: METRICS_DOMAIN
          value: knative.dev/sources
        - name: CONFIG_OBSERVABILITY_NAME
          value: config-observability
        - name: CONFIG_LEADERELECTION_NAME
          value: config-leader-election-integration-scheduler
        - name: WAITQUEUE_PRODUCER_IMAGE
          value: harbor.eurekacloud.io/eureka/kraken-waitqueue-producer:latest
        - name: WAITQUEUE_PROCESSOR_IMAGE
          value: harbor.eurekacloud.io/eureka/kraken-waitqueue-processor:latest
        volumeMounts:
        resources:
          requests:
            cpu: 20m
            memory: 20Mi
      imagePullSecrets:
      - name: docker-registry-secret
      serviceAccount: integration-scheduler-manager
      terminationGracePeriodSeconds: 10