apiVersion: s4.sap.com/v1

kind: Hana
metadata:
  name: {{ template "fullname" . }}-hana
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  finalizers:
  - finalizer.s4.sap.com
spec:
  secretName: {{ template "fullname" . }}-hana

