apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- if .Values.discovery.enabled }}
    role: {{.Values.discovery.role}}
    host: {{.Values.discovery.host}}
{{- end}}
{{- if .Values.prometheus.enabled }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: {{.Values.prometheus.path}}
{{- end}}
spec:
  ports:
    - port: 80
{{- if .Values.role_permission_sidecar.enabled }}
      targetPort: 80
{{- else }}
      targetPort: {{ .Values.service.port}}
{{- end }}
  selector:
    app: {{ template "name" . }}
    release: {{ .Release.Name }}
