/*
Copyright 2020 The Knative Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	v1alpha1 "kraken.dev/kraken-scheduler/pkg/apis/scheduler/v1alpha1"
)

// FakeIntegrationScenarios implements IntegrationScenarioInterface
type FakeIntegrationScenarios struct {
	Fake *FakeSchedulerV1alpha1
	ns   string
}

var integrationscenariosResource = schema.GroupVersionResource{Group: "scheduler.kraken.dev", Version: "v1alpha1", Resource: "integrationscenarios"}

var integrationscenariosKind = schema.GroupVersionKind{Group: "scheduler.kraken.dev", Version: "v1alpha1", Kind: "IntegrationScenario"}

// Get takes name of the integrationScenario, and returns the corresponding integrationScenario object, and an error if there is any.
func (c *FakeIntegrationScenarios) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.IntegrationScenario, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(integrationscenariosResource, c.ns, name), &v1alpha1.IntegrationScenario{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.IntegrationScenario), err
}

// List takes label and field selectors, and returns the list of IntegrationScenarios that match those selectors.
func (c *FakeIntegrationScenarios) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.IntegrationScenarioList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(integrationscenariosResource, integrationscenariosKind, c.ns, opts), &v1alpha1.IntegrationScenarioList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.IntegrationScenarioList{ListMeta: obj.(*v1alpha1.IntegrationScenarioList).ListMeta}
	for _, item := range obj.(*v1alpha1.IntegrationScenarioList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested integrationScenarios.
func (c *FakeIntegrationScenarios) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(integrationscenariosResource, c.ns, opts))

}

// Create takes the representation of a integrationScenario and creates it.  Returns the server's representation of the integrationScenario, and an error, if there is any.
func (c *FakeIntegrationScenarios) Create(ctx context.Context, integrationScenario *v1alpha1.IntegrationScenario, opts v1.CreateOptions) (result *v1alpha1.IntegrationScenario, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(integrationscenariosResource, c.ns, integrationScenario), &v1alpha1.IntegrationScenario{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.IntegrationScenario), err
}

// Update takes the representation of a integrationScenario and updates it. Returns the server's representation of the integrationScenario, and an error, if there is any.
func (c *FakeIntegrationScenarios) Update(ctx context.Context, integrationScenario *v1alpha1.IntegrationScenario, opts v1.UpdateOptions) (result *v1alpha1.IntegrationScenario, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(integrationscenariosResource, c.ns, integrationScenario), &v1alpha1.IntegrationScenario{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.IntegrationScenario), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeIntegrationScenarios) UpdateStatus(ctx context.Context, integrationScenario *v1alpha1.IntegrationScenario, opts v1.UpdateOptions) (*v1alpha1.IntegrationScenario, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(integrationscenariosResource, "status", c.ns, integrationScenario), &v1alpha1.IntegrationScenario{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.IntegrationScenario), err
}

// Delete takes name of the integrationScenario and deletes it. Returns an error if one occurs.
func (c *FakeIntegrationScenarios) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(integrationscenariosResource, c.ns, name), &v1alpha1.IntegrationScenario{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeIntegrationScenarios) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(integrationscenariosResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.IntegrationScenarioList{})
	return err
}

// Patch applies the patch and returns the patched integrationScenario.
func (c *FakeIntegrationScenarios) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.IntegrationScenario, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(integrationscenariosResource, c.ns, name, pt, data, subresources...), &v1alpha1.IntegrationScenario{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.IntegrationScenario), err
}
